### ISSUE TITLE
Horizontally cramped

### ISSUE THREAD

**Issue by Micket** [OSC/bc_js_filepicker#205]
My favorite paths are a longer than average, window doesn't react, overflows the text.

Even with the app in full screen the directory`/cephyr/NOBACKUP/groups/alvis` is enough to overflow;

![2023-09-12-144330_3968x1152_scrot](https://github.com/OSC/bc_js_filepicker/assets/72749/95e46a58-78ba-4cc5-a862-a799837b01bf)

Even If I happen to squeeze the window a tiny bit, it breaks even further making things way to cramped for almost everything, despite there being a lot of horizontal space that could be used.
![2023-09-12-190014_3968x1152_scrot](https://github.com/OSC/bc_js_filepicker/assets/72749/8df59e5b-ffcf-4ad6-b4bd-6c6807e04ac5)

Is there a way to easily customize the margins used here?

**Comment by johrstrom** [comment]
Hi, thanks for the ticket - but I have to say it won't be worked. This is being replaced in 3.1 with a native path_selector widget.

https://github.com/OSC/ondemand/issues/1571

That said - it (the newer implementation) doesn't show favorites at all at the moment (and likely won't in 3.1 because it's coming soon) but I made a ticket for the same. And I'll be sure to link that ticket back to these 2 for the same - it should account for your setup.
